---

linux:
  source: https://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.2.zip
windows:
  app_dir: "C:\\Program Files\\Amazon\\AmazonCloudWatchAgent"
  package: AmazonCloudWatchAgent
